# Generated by Django 3.2.4 on 2021-07-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='noimage.png', upload_to='media'),
        ),
    ]
