# Generated by Django 3.2.4 on 2021-06-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sale', '0002_alter_sale_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='created',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
