# Generated by Django 3.2.4 on 2021-06-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sale', '0003_auto_20210617_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
