# Generated by Django 3.2.4 on 2021-06-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sale', '0004_auto_20210617_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
